version: '3'

services:
  webserver:
    image: nginx:latest
    ports:
      - 8001:80
      - 433:433
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/
    links:
      - php-fmp
      - db
    networks:
      - app-network

  php-fmp:
    build: docker/php-fmp
    volumes:
      - ./:/var/www/html/
      - ./docker/php-fmp/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - 9000:9000
    links:
      - db
    networks:
      - app-network

  db:
    image: mysql
    ports:
      - 3307:3306
    volumes:
      - /var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=guest_book
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=docker
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
