version: "3"
services:

    mysql:
      image: mysql:5.6
      container_name: guest-book-mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      working_dir: /application
      volumes:
        - ./phpdocker/database/:/docker-entrypoint-initdb.d
        - dbdata:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=guest_book
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "3307:3306"
      networks:
        - custom

    webserver:
      image: nginx:alpine
      container_name: guest-book-webserver
      working_dir: /application/web
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"
      networks:
        - custom

    php-fpm:
      build: phpdocker/php-fpm
      container_name: guest-book-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      networks:
        - custom

networks:
  custom:
    driver: bridge
volumes:
  dbdata:
    driver: local
